baseURL = "https://py563.github.io/"
languageCode = "en-us"
title = "PY563"
theme = "hugo-resume"
enableGitInfo = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4
    style = "tango"

[taxonomies]
    tag = "tags"

[params]
    firstName = "Prajwal"
    lastName = "Maredukonda"
    address = "Warangal, TG, India"
    contactNote = "Java and Python Developer"
    profileImage = "img/TechChat.png"
    email = "prajwalyashasvi@yahoo.co.in"
    description = "Prajwal has around five years of experience as developer in Java, Python & SQL. He worked in Cyber Security Research, Unemployment Insurance, and Travel domains."
    favicon = "images/favicon.ico"
    
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    publicationsAlternateName = "Presentations"
    showExperience = true
    showEducation = true
    showBlog = true
    showQr = true

	# do you want to show git hash on page footer and link to repo? Add commit prefix here.
    gitCommitPrefix = "https://github.com/py563/cv-hugo/commit/"
	
[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/prajwalyashasvi/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/py563/"

[[params.handles]]
    name = "GitLab"
    link = "https://gitlab.com/PY563"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/py563"

[[params.handles]]
    link = "https://keybase.io/prajwalyashasvi"
    name = "Keybase"

[params.google.analytics]
    trackerID = "UA-162845368-2"
    
[outputs]
home = ["HTML", "JSON"]