baseURL = "https://prajwalyashasvi.in/"
languageCode = "en-us"
title = "PY563"
theme = "hugo-resume"
enableGitInfo = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4
    style = "tango"

[taxonomies]
    tag = "tags"

[params]
    firstName = "Prajwal"
    lastName = "Maredukonda"
    address = "Warangal, TG, India"
    contactNote = "Software Engineer and/home/vce-wsl/gitDebRepos/cv-hugo/content/projects Assistant Professor"
    profileImage = "img/TechChat.jpeg"
    email = "hello@prajwalyashasvi.in"
    description = "Prajwal has around six years of experience as a programmer in Java, Python & SQL. He also teaches Computer Science courses at an engineering college."
    favicon = "/favicon.ico"
    
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    publicationsAlternateName = "Presentations"
    showExperience = true
    showEducation = true
    showBlog = true
    showQr = true

	# do you want to show git hash on page footer and link to repo? Add commit prefix here.
    gitCommitPrefix = "https://github.com/py563/cv-hugo/commit/"
	
[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/prajwalyashasvi/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/py563/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/py563"

[[params.handles]]
    link = "https://keybase.io/prajwalyashasvi"
    name = "Keybase"

[permalinks]
  publications = "/presentations/:title/"
    
[outputs]
home = ["HTML", "JSON"]